# Generated by Django 5.2.8 on 2025-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_usuario_is_active_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('CARGA_MASIVA', 'Carga Masiva'), ('LOGOUT', 'Cierre de Sesión'), ('MFA_SETUP', 'Configuración MFA'), ('MFA_DISABLE', 'Desactivación MFA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
