# Generated by Django 5.2.8 on 2025-11-12 03:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('ejercicio', models.IntegerField()),
                ('mercado', models.CharField(choices=[('ACN', 'Acciones'), ('CFI', 'CFI'), ('Fondos_Mutuos', 'Fondos Mutuos')], max_length=15)),
                ('instrumento', models.CharField(max_length=50)),
                ('fecha_pago', models.DateField()),
                ('descripcion_dividendo', models.TextField(blank=True, null=True)),
                ('secuencia_evento', models.IntegerField(blank=True, null=True)),
                ('numero_dividendo', models.IntegerField(default=0)),
                ('tipo_sociedad', models.CharField(blank=True, choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('acogido_isfut', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('Sistema', 'Sistema'), ('Corredor', 'Corredor'), ('Carga_Masiva', 'Carga Masiva')], max_length=15)),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'CALIFICACION_TRIBUTARIA',
                'ordering': ['-ejercicio', 'mercado', 'instrumento'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Analista', 'Analista'), ('Corredor', 'Corredor'), ('Auditor', 'Auditor')], max_length=20)),
                ('contraseña_hash', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='FactorCalificacion',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('factor_8', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_9', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_10', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_11', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_12', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_13', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_14', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_15', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_16', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_17', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_18', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_19', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_20', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_21', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_22', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_23', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_24', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_25', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_26', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_27', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_28', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_29', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_30', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_31', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_32', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_33', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_34', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_35', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_36', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('factor_37', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('id_calificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factorcalificacion', to='calificaciones.calificaciontributaria')),
            ],
            options={
                'verbose_name': 'Factor de Calificación',
                'verbose_name_plural': 'Factores de Calificación',
                'db_table': 'FACTOR_CALIFICACION',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('CARGA_MASIVA', 'Carga Masiva'), ('LOGOUT', 'Cierre de Sesión')], max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('id_calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.calificaciontributaria')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calificaciones.usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'LOG_AUDITORIA',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calificaciones.usuario'),
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(choices=[('DJ1948', 'DJ1948'), ('CSV_FACTORES', 'CSV_FACTORES')], max_length=15)),
                ('tamano', models.BigIntegerField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado_proceso', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_error', models.IntegerField(default=0)),
                ('errores_detalle', models.TextField(blank=True, null=True)),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calificaciones.usuario')),
            ],
            options={
                'verbose_name': 'Archivo de Carga',
                'verbose_name_plural': 'Archivos de Carga',
                'db_table': 'ARCHIVO_CARGA',
            },
        ),
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together={('ejercicio', 'mercado', 'instrumento', 'secuencia_evento')},
        ),
    ]
