# Generated by Django 5.2.8 on 2025-11-12 01:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(help_text='Año comercial', verbose_name='Ejercicio Comercial')),
                ('mercado', models.CharField(choices=[('ACN', 'Acciones'), ('CFI', 'CFI'), ('FON', 'Fondos Mutuos')], max_length=3, verbose_name='Tipo de Mercado')),
                ('instrumento', models.CharField(max_length=50, verbose_name='Instrumento')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago del Dividendo')),
                ('secuencia_evento', models.IntegerField(default=10000, help_text='Secuencia superior a 10.000', verbose_name='Secuencia del Evento de Capital')),
                ('numero_dividendo', models.IntegerField(default=0, verbose_name='Número de Dividendo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Dividendo')),
                ('tipo_sociedad', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1, verbose_name='Tipo de Sociedad')),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Valor Histórico')),
                ('acogido_isfut', models.BooleanField(default=False, verbose_name='Acogido a ISFUT/ISIFT')),
                ('origen', models.CharField(choices=[('corredor', 'Corredor'), ('sistema', 'Sistema'), ('archivo', 'Archivo Carga Masiva')], default='corredor', max_length=20, verbose_name='Origen de la Información')),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Factor de Actualización')),
                ('factor_8', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Con crédito por IDPC generados a contar del 01.01.2017')),
                ('factor_9', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Con crédito por IDPC acumulados hasta el 31.12.2016')),
                ('factor_10', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Con derecho a crédito por pago de IDPC voluntario')),
                ('factor_11', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Sin derecho a crédito')),
                ('factor_12', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Rentas provenientes del registro RAP y Diferencia Inicial de sociedad acogida al ex Art. 14 TER A) LIR')),
                ('factor_13', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Otras rentas percibidas Sin Prioridad en su orden de imputación')),
                ('factor_14', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Exceso Distribuciones Desproporcionadas (N°9 Art.14 A)')),
                ('factor_15', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Utilidades afectadas con impuesto sustitutivo al FUT (ISFUT) Ley N°20.780')),
                ('factor_16', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Rentas generadas hasta el 31.12.1983 y/o utilidades afectadas con impuesto sustitutivo al FUT (ISFUT) LEY N°21.210')),
                ('factor_17', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Rentas Exentas de Impuesto Global Complementario (IGC) (Artículo 11, Ley 18.401), Afectas a Impuesto Adicional')),
                ('factor_18', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Rentas Exentas de Impuesto Global Complementario (IGC) y/o Impuesto Adicional (IA)')),
                ('factor_19', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Ingresos No Constitutivos de Renta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-ejercicio', 'mercado', 'instrumento'],
                'unique_together': {('ejercicio', 'mercado', 'instrumento', 'secuencia_evento')},
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('carga_masiva', 'Carga Masiva')], max_length=20)),
                ('descripcion', models.TextField()),
                ('usuario', models.CharField(max_length=100)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='calificaciones.calificaciontributaria')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
