# Generated by Django 5.2.8 on 2025-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_remove_usuario_is_active_alter_logauditoria_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='usuario_nombre',
            field=models.CharField(blank=True, help_text='Nombre del usuario responsable al momento del log', max_length=150, null=True),
        ),
    ]
