# Generated by Django 5.2.8 on 2025-12-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_usuario_failed_login_attempts_usuario_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('LOGIN_FAIL', 'Inicio de Sesión Fallido'), ('LOCK_ACCOUNT', 'Cuenta Bloqueada'), ('CARGA_MASIVA', 'Carga Masiva'), ('LOGOUT', 'Cierre de Sesión'), ('MFA_SETUP', 'Configuración MFA'), ('MFA_DISABLE', 'Desactivación MFA')], max_length=50),
        ),
    ]
